### ISSUE TITLE
Return type of Document.save 

### ISSUE THREAD

**Issue by takeshi-nishida** [louy/typed-mongoose#1]
It seems that `save<T>(callback?: (err: any, res: T) => void): Promise<void>;` should be `save<T>(callback?: (err: any, res: T) => void): Promise<T>;`. I'm new to typings and GitHub too, so I wanted to make sure that I'm not making a terrible mistake, if I should create a PR.

Thanks!

**Comment by louy** [comment]
[You're right!](http://mongoosejs.com/docs/api.html#document_Document-save) feel free to submit a PR.
